# Generated by Django 4.1.7 on 2023-03-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
